-- -- markdown preview `:MarkdownPreviewToggle`
-- use({
-- 	"iamcco/markdown-preview.nvim",
-- 	run = function()
-- 		vim.fn["mkdp#util#install"]()
-- 	end,
-- })
--
-- -- git
-- use({ "tpope/vim-fugitive" })
--
--
-- use({
-- 	"lewis6991/satellite.nvim",
-- })
--
-- -- help for coding Lua Neovim
-- use("folke/neodev.nvim")
--
-- -- use "lukas-reineke/lsp-format.nvim"
