# https://starship.rs/config/
'$schema' = 'https://starship.rs/config-schema.json'

palette = 'dracula'

[character]
success_symbol = '[󰐊](green)'
error_symbol = '[󰐊](red)'

[directory]
truncate_to_repo = false
style = 'comment'
format = '[](purple) [$path]($style)[$read_only]($read_only_style) '

[git_branch]
style = 'pink'
symbol = ''
format = '[\($symbol$branch(:$remote_branch)\)]($style) '

[git_status]
# "nf-oct" -> https://www.nerdfonts.com/cheat-sheet
#                              
conflicted = ' '
ahead = ' '
behind = ' '
diverged = ' '
up_to_date = ''
untracked = ' '
stashed = ' '
modified = '⚡'
staged = ' '
renamed = ' '
deleted = ' '
typechanged = ''
format = '([$all_status$ahead_behind]($style) )'

[palettes.dracula]
background = '#282a36'
current_line = '#44475a'
foreground = '#f8f8f2'
comment = '#6272a4'
cyan = '#8be9fd'
green = '#50fa7b'
orange = '#ffb86c'
pink = '#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'
